"""change to nullable

Revision ID: 3249e3d1d36d
Revises: b2804df715ed
Create Date: 2023-11-10 21:47:24.371122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3249e3d1d36d'
down_revision: Union[str, None] = 'b2804df715ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('train', 'from_station_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('train', 'to_station_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vagon_location_stream', 'dislocation_station_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vagon_location_stream', 'to_station_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vagon_location_stream', 'to_station_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vagon_location_stream', 'dislocation_station_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('train', 'to_station_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('train', 'from_station_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
