"""drop table

Revision ID: 0db4ae3b0b99
Revises: 3249e3d1d36d
Create Date: 2023-11-10 22:54:04.096122

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0db4ae3b0b99'
down_revision: Union[str, None] = '3249e3d1d36d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vagon_location_stream')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    raise NotImplemented
    # ### end Alembic commands ###
