"""create inital tables

Revision ID: b2804df715ed
Revises: 6ae5475e9aec
Create Date: 2023-11-10 19:41:05.151384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b2804df715ed'
down_revision: Union[str, None] = '6ae5475e9aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('station__id__idx', 'station', ['id'], unique=False)
    op.create_table('vagon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('vagon__id__idx', 'vagon', ['id'], unique=False)
    op.create_table('peregon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_station_id', sa.Integer(), nullable=False),
    sa.Column('to_station_id', sa.Integer(), nullable=False),
    sa.Column('len_km', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['from_station_id'], ['station.id'], ),
    sa.ForeignKeyConstraint(['to_station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('peregon__from_station_id__idx', 'peregon', ['from_station_id'], unique=False)
    op.create_index('peregon__to_station_id__idx', 'peregon', ['to_station_id'], unique=False)
    op.create_table('train',
    sa.Column('train_index', sa.String(length=32), nullable=False),
    sa.Column('from_station_id', sa.Integer(), nullable=False),
    sa.Column('to_station_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_station_id'], ['station.id'], ),
    sa.ForeignKeyConstraint(['to_station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('train_index')
    )
    op.create_index('train__from_station_id__idx', 'train', ['from_station_id', 'to_station_id'], unique=False)
    op.create_index('train__number__idx', 'train', ['number'], unique=False)
    op.create_index('train__to_station_id__idx', 'train', ['to_station_id', 'from_station_id'], unique=False)
    op.create_index('train__train_index__idx', 'train', ['train_index'], unique=False)
    op.create_table('vagon_location_stream',
    sa.Column('vagon_id', sa.Integer(), nullable=False),
    sa.Column('moment', sa.DateTime(), nullable=False),
    sa.Column('dislocation_station_id', sa.Integer(), nullable=False),
    sa.Column('to_station_id', sa.Integer(), nullable=False),
    sa.Column('train_index', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['dislocation_station_id'], ['station.id'], ),
    sa.ForeignKeyConstraint(['to_station_id'], ['station.id'], ),
    sa.ForeignKeyConstraint(['train_index'], ['train.train_index'], ),
    sa.ForeignKeyConstraint(['vagon_id'], ['vagon.id'], ),
    sa.PrimaryKeyConstraint('vagon_id', 'moment')
    )
    op.create_index('stream__train_index__idx', 'vagon_location_stream', ['train_index', 'moment', 'vagon_id'], unique=False)
    op.create_index('stream__vagon_id__idx', 'vagon_location_stream', ['vagon_id', 'moment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('stream__vagon_id__idx', table_name='vagon_location_stream')
    op.drop_index('stream__train_index__idx', table_name='vagon_location_stream')
    op.drop_table('vagon_location_stream')
    op.drop_index('train__train_index__idx', table_name='train')
    op.drop_index('train__to_station_id__idx', table_name='train')
    op.drop_index('train__number__idx', table_name='train')
    op.drop_index('train__from_station_id__idx', table_name='train')
    op.drop_table('train')
    op.drop_index('peregon__to_station_id__idx', table_name='peregon')
    op.drop_index('peregon__from_station_id__idx', table_name='peregon')
    op.drop_table('peregon')
    op.drop_index('vagon__id__idx', table_name='vagon')
    op.drop_table('vagon')
    op.drop_index('station__id__idx', table_name='station')
    op.drop_index('idx_station_location', table_name='station', postgresql_using='gist')
    op.drop_table('station')
    # ### end Alembic commands ###
