"""restore stream table

Revision ID: 6f8817c70b38
Revises: 0db4ae3b0b99
Create Date: 2023-11-10 23:01:43.526807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f8817c70b38'
down_revision: Union[str, None] = '0db4ae3b0b99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vagon_location_stream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vagon_id', sa.Integer(), nullable=False),
    sa.Column('moment', sa.DateTime(), nullable=True),
    sa.Column('dislocation_station_id', sa.Integer(), nullable=True),
    sa.Column('to_station_id', sa.Integer(), nullable=True),
    sa.Column('train_index', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['dislocation_station_id'], ['station.id'], ),
    sa.ForeignKeyConstraint(['to_station_id'], ['station.id'], ),
    sa.ForeignKeyConstraint(['train_index'], ['train.train_index'], ),
    sa.ForeignKeyConstraint(['vagon_id'], ['vagon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('stream__train_index__idx', 'vagon_location_stream', ['train_index', 'moment', 'vagon_id'], unique=False)
    op.create_index('stream__vagon_id__idx', 'vagon_location_stream', ['vagon_id', 'moment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('stream__vagon_id__idx', table_name='vagon_location_stream')
    op.drop_index('stream__train_index__idx', table_name='vagon_location_stream')
    op.drop_table('vagon_location_stream')
    # ### end Alembic commands ###
